### ISSUE TITLE
フィッシングの項目につきまして

### ISSUE THREAD

**Issue by mashharuki** [cgtf/user-guidance#1]
> 検索して表示されるサイトが、必ずしも正しい（少なくとも悪意がない）とは限りません。
> 
> 検索結果の上位に、悪意のあるサイトの広告や、正規のサイトを模倣したサイト（偽サイト）が表示されている場合があります。検索結果については十分に確認することが必要です。
> 
> また、メールやSMSで届いたURLも、悪意のあるサイトへ誘導される場合があります。
> 

トラブル集のフィンシングの項目につきまして、メールやSMSで偽サイトへ誘導するURLを送りつけるパターンの他、プロジェクトのDiscord上でも偽サイトへの誘導が行われているパターンも多く見受けられます。

その際に、運営の管理者のユーザーが乗っ取られ、偽サイトへ誘導するURLを貼り付けて実際にユーザーが誘導されNFT等を抜き取られてしまっているケースもあるため、Discord上での応募キャンペーンを装った通知等には注意して確認する旨の記載もあった方が良いのではないかと感じました。

※ プロジェクトで計画しているNFTのミントスケジュールとは明らかに異なるタイミングで応募キャンペーンの通知を行ってきた場合など・・。

**Comment by niwatako** [comment]
ご意見ありがとうございます。お返事が遅くなってしまい恐れ入ります。
ご指摘のようなトラブルについて、類似のケースをいくつか取り上げておりますので、それらを確認させてください。

「フィッシング」カテゴリには、現時点で下記の4ケースがございます。

- [検索結果の一番上のものにアクセスしたら悪意のあるサイトだった](https://cgtf.github.io/user-guidance/troubles/phishing/search-results/)
- [暗号資産で支払った先が架空のショッピングサイトだった](https://cgtf.github.io/user-guidance/troubles/phishing/electronic-commerce/)
- [SNSで告知されていた取引所のキャンペーンが、実は偽物だった](https://cgtf.github.io/user-guidance/troubles/phishing/sns/)
- [取引所からのメールが実は偽物だった](https://cgtf.github.io/user-guidance/troubles/phishing/mail/)

これらに加えて、特にご指摘いただいたような手口がNFTに関連してありうることから、「NFT」のカテゴリに下記のケースを取り上げています。

- [NFTの販売情報が偽物だった](https://cgtf.github.io/user-guidance/troubles/nft/impersonation/)

私達としては、Discordでのご指摘のような手口は、[SNSで告知されていた取引所のキャンペーンが、実は偽物だった](https://cgtf.github.io/user-guidance/troubles/phishing/sns/)と
[NFTの販売情報が偽物だった](https://cgtf.github.io/user-guidance/troubles/nft/impersonation/)でカバーできると考えておりましたので、一度これらのケースをご確認いただければと存じます。

その上で、現状の各ケースの解説では不十分か、新たにケースを追加するべきか、より伝わりやすいように既存のケースの表現を修正するべきかなど、ご意見をお伺いできれば幸いです。

**Comment by mashharuki** [comment]
@niwatako ご確認いただきましてありがとうございます！上記につきまして承知いたしました！いただいたリンク先の内容を確認するようにいたします。

**Comment by niwatako** [comment]
こちら一旦クローズさせていただきます。
改めてご意見ございましたら新規Issueを建てていただければと存じます。
